### ISSUE TITLE
error in Template

### ISSUE THREAD

**Issue by hphd70** [yohaybn/HomeAssistant-EPG#17]
I am trying to get the epg data from sender "3sat".

A sensor (sensor.3sat) has been created with correct attributes:
```
today: 
'19:00':
  title: heute
  desc: vom 02.02.2025, 19:00:00 Uhr
  start: '19:00'
  end: '19:08'
'19:08':
  title: 3sat-Wetter
  desc: ''
  start: '19:08'
  end: '19:10'
'19:10':
  title: NZZ Format
  desc: >-
    Abgestumpft vom Weltchaos? - Was die Flut der Schreckensmeldungen mit uns
    macht
  start: '19:10'
  end: '19:40'
```

in Template-Editor:
{{ states('sensor.3sat') }} gives the correct info

but when I enter:
```
{% for time in states.sensor.3sat.attributes.today -%}
  {% set program=states.sensor.3sat.attributes.today[time] %}
    <details>  
    <summary>{{time}}: {{ program.title}}</summary>
      {{ program.desc}}
    </details>
  {%- endfor %}

```

following message appears:

`TemplateSyntaxError: expected token 'end of statement block', got 'sat'`

The code above with other sender (e.g. "sat_1") returns the correct info:

```
{% for time in states.sensor.sat_1.attributes.today -%}
  {% set program=states.sensor.sat_1.attributes.today[time] %}
    <details>  
    <summary>{{time}}: {{ program.title}}</summary>
      {{ program.desc}}
    </details>
  {%- endfor %}
```

```
<details>  
    <summary>19:55: Skischule Salar</summary>
      Folge 03: Franco Marvulli
    </details>
    <details>  
    <summary>20:15: Der Prinz aus Zamunda 2</summary>
      
    </details>
    <details>  
    <summary>22:30: Vacation Friends</summary>
      
    </details>

```

What can I do to get the epg data from "3 Sat"?

thanks for your support!
