### ISSUE TITLE
Sensor not getting filled

### ISSUE THREAD

**Issue by jacky-coke** [yohaybn/HomeAssistant-EPG#4]
Hi, 

just installed your integration but have difficulties receiving epg-information. 
Once setup, I manually called the service to create / update the corresponding sensor like shown below: 

```
service: epg.track_channel
data:
    file: germanypremium
    channel_id: ZDFinfo.de
```

Creation of the sensor happens, but seems to stay empty afterwards: 

<img width="1045" alt="image" src="https://github.com/user-attachments/assets/a326f71c-6759-483e-b572-f267511e937a">

Any suggestions?
